use_frameworks!

def standard_pods
    pod 'RecorderFramework', :path => '../'
end

target 'RecorderFramework-MacExample’ do
  standard_pods
end

target 'RecorderFramework-TVExample’ do
  standard_pods
end

target 'RecorderFramework-WatchExample’ do
  standard_pods
end

target 'RecorderFramework-WatchExample Extension’ do
  standard_pods
end

target 'RecorderFramework_Example' do
  standard_pods
  pod 'FDWaveformView'
  pod 'Bugsee'
  pod 'Firebase/Core'
end

target 'RecorderFramework_Tests' do
    standard_pods
 end
