use_frameworks!

def standard_pods
    pod 'RecorderFramework', :path => '../'
end

target 'RecorderFramework-MacExample’ do
  standard_pods
end

target 'RecorderFramework-TVExample’ do
  standard_pods
end

target 'RecorderFramework-WatchExample’ do
  standard_pods
end

target 'RecorderFramework-WatchExample Extension’ do
  standard_pods
end

target 'RecorderFramework_Example' do
  standard_pods
  pod 'FDWaveformView'
  pod 'Bugsee'
  pod 'ShareFramework', :git => 'https://Grif@bitbucket.org/Grif/shareframework.git'
end

target 'RecorderFramework_Tests' do
    standard_pods
end

post_install do |installer|  
    installer.pods_project.targets.each do |target|  
        target.build_configurations.each do |config|  
            if config.build_settings['SDKROOT'] == 'watchos'  
              config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '3.2'  
            end  
        end  
    end  
end 
